apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: file-reader
  name: file-reader
spec:
  replicas: 3
  selector:
    matchLabels:
      app: file-reader
  template:
    metadata:
      labels:
        app: file-reader
    spec:
      containers:
      - image: k8sprimer.azurecr.io/demo/file_reader:1
        name: file-reader
        resources:
          requests:
            cpu: 1
