apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: producer
  name: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - image: primer:1234/producer:1
        name: producer
        resources:
          requests:
            cpu: 1
        envFrom:
        - configMapRef:
            name: producer-config