FROM docker.io/python:3.8
WORKDIR /app
COPY ./consumer.conf .
COPY ./consumer.py .
COPY ./requirements.txt .
ENV PYTHONUNBUFFERED=1 
ENV RABBITMQ_USERNAME=guest 
ENV RABBITMQ_PASSWORD=guest 
RUN pip install -r requirements.txt
ENTRYPOINT ["python3", "-m", "consumer"]
