# vim: set foldmethod=marker:
# Default values for exercise4.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

##############################     <Consumer>     ##############################{{{
consumer:
  config:
    configMapName: consumer-conf-file
    configMountPath: "/config"
    readOnly: true
  env:
    - name: RABBITMQ_USERNAME
      value: "guest"
    - name: RABBITMQ_PASSWORD
      value: "guest"
    - name: CONFIG_PATH
      value: "/config"
    - name: PYTHONUNBUFFERED
      value: "1"
  fullnameOverride: ""
  image:
    repository: primer:1234/consumer
    pullPolicy: IfNotPresent
    tag: "1"
  imagePullPolicy: IfNotPresent
  nameOverride: ""
  podAnnotations: {}
  replicaCount: 1
  resources:
    requests:
      cpu: 200m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 128Mi
  restartPolicy: Always
#############################     </Consumer>     #############################}}}

##############################     <Producer>     ##############################{{{
producer:
  env:
    - name: RABBITMQ_USERNAME
      value: "guest"
    - name: RABBITMQ_PASSWORD
      value: "guest"
    - name: SIGNAL_TYPE
      value: "sine"
    - name: SIGNAL_SAMPLE_INTERVAL
      value: "0.2s"
  fullnameOverride: ""
  image:
    repository: primer:1234/producer
    pullPolicy: IfNotPresent
    tag: "2"
  imagePullPolicy: IfNotPresent
  nameOverride: ""
  podAnnotations: {}
  replicaCount: 3
  resources:
    requests:
      cpu: 200m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 128Mi
  restartPolicy: Always
#############################     </Producer>     #############################}}}
